version: "3.5"
services:
  echoserver:
    build:
      args:
        BIN_NAME: echoserver
      context: ../build/bin
      dockerfile: ../../deployments/Dockerfile
    image: zephinzer/demo-echoserver:latest
    ports:
      - 11111:11111
  echoservers:
    build:
      args:
        BIN_NAME: echoservers
      context: ../build/bin
      dockerfile: ../../deployments/Dockerfile
    image: zephinzer/demo-echoservers:latest
    ports:
      - 11112:11111
    volumes:
      - ../assets/certs/server.crt:/etc/ssl/server.crt:ro
      - ../assets/keys/server.key:/etc/ssl/server.key:ro
  fwdserver:
    build:
      args:
        BIN_NAME: fwdserver
      context: ../build/bin
      dockerfile: ../../deployments/Dockerfile
    image: zephinzer/demo-fwdserver:latest
    environment:
      ECHOSERVER1: http://echoserver:11111
      ECHOSERVER2: https://echoservers:11111
    ports:
      - 11113:11111
    volumes:
      - ../assets/certs/server.crt:/etc/ssl/server.crt:ro
      - ../assets/keys/server.key:/etc/ssl/server.key:ro
