apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcheck
  namespace: go-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: healthcheck
      type: cmd
  template:
    metadata:
      labels:
        app: healthcheck
        type: cmd
    spec:
      containers:
      - name: healthcheck
        image: zephinzer/demo-healthcheck:latest
        envFrom:
          - configMapRef:
              name: healthcheck
        readinessProbe:
          httpGet:
            path: /readiness
            port: 11114
          initialDelaySeconds: 5
          periodSeconds: 2
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /liveness
            port: 11114
          initialDelaySeconds: 5
          periodSeconds: 2
          failureThreshold: 5
        resources:
          requests:
            memory: 10Mi
            cpu: 10m
          limits:
            memory: 15Mi
            cpu: 20m
        ports:
        - containerPort: 11114

---

apiVersion: v1
kind: Service
metadata:
  name: healthcheck
  namespace: go-demo
spec:
  selector:
    app: healthcheck
    type: cmd
  ports:
  - port: 11114
    targetPort: 11114

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: healthcheck
  namespace: go-demo
data:
  PORT: "11114"
  HEALTHY: "true"
  READY: "true"
